spring:
    application:
        name: poe-gamble
    datasource:
        url: jdbc:postgresql://43.203.98.225:4202/poegamble_test
        username: poetest
        password: Alstn124124@@
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              format_sql: true
              globally_quoted_identifiers: true
server:
    port: 8080


springdoc:
    swagger-ui:
        path: /api/docs
        groups-order: desc
        tags-sorter: alpha
        default-models-expand-depth: -1
    paths-to-match: /api/v1/**