spring:
    application:
        name: poe-gamble
    datasource:
        url: jdbc:h2:./db
        username: username
        password: password
        driver-class-name: org.h2.Driver
    h2:
      console:
          enabled: true
          settings:
              web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              format_sql: true
server:
    port: 8080


springdoc:
    swagger-ui:
        path: /api/docs
        groups-order: desc
        tags-sorter: alpha
        default-models-expand-depth: -1
    paths-to-match: /api/v1/**