spring:
    application:
        name: poe-gamble
    datasource:
        url: jdbc:h2:mem:test
        username: username
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 8080
